server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/phep   # use 5433 if you run phep-pg; use 5432 if you connect to existing
    username: phep
    password: phep
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    locations: classpath:db/migration
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
# application.yml
springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true

---
spring.config.activate.on-profile: prod
springdoc:
  api-docs.enabled: false
  swagger-ui.enabled: false
