name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Helpful diagnostics for Testcontainers
      - name: Docker info
        run: |
          docker --version
          docker info

      # Build & run tests (integration tests included)
      - name: Build & test
        run: ./mvnw -B -U verify
